CREATE TABLE IF NOT EXISTS pipeline_runs (
    run_id SERIAL PRIMARY KEY,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    stage_1_status VARCHAR(20) DEFAULT 'waiting',
    stage_1_start TIMESTAMP,
    stage_1_end TIMESTAMP,
    stage_2_status VARCHAR(20) DEFAULT 'waiting',
    stage_2_start TIMESTAMP,
    stage_2_end TIMESTAMP,
    stage_3_status VARCHAR(20) DEFAULT 'waiting',
    stage_3_start TIMESTAMP,
    stage_3_end TIMESTAMP,
    stage_4_status VARCHAR(20) DEFAULT 'waiting',
    stage_4_start TIMESTAMP,
    stage_4_end TIMESTAMP,
    stage_5_status VARCHAR(20) DEFAULT 'waiting',
    stage_5_start TIMESTAMP,
    stage_5_end TIMESTAMP,
    stage_6_status VARCHAR(20) DEFAULT 'waiting',
    stage_6_start TIMESTAMP,
    stage_6_end TIMESTAMP,
    stage_7_status VARCHAR(20) DEFAULT 'waiting',
    stage_7_start TIMESTAMP,
    stage_7_end TIMESTAMP
);